MicroBlog/config/routes.rb
Rails.application.routes.draw do
  root 'blogs#index'
  resources :blogs do
    member do
      get :publish
    end
    resources :comments
  end
end

MicroBlog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MicroBlog/app/models/blog.rb
class Blog < ApplicationRecord
  extend FriendlyId

  friendly_id :title, use: :slugged
  has_many :comments
  validates :title, presence: true, length: {minimum: 5}
  validates :body, presence: true, length: {minimum: 10}
end

MicroBlog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
end

MicroBlog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

MicroBlog/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :find_id, only: [:edit, :publish, :destroy]

  def index
    @blogs = Blog.all
  end

  def show
    @blog = Blog.friendly.find(params[:id])
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)

    if @blog.save
      redirect_to @blog
    else
      render :new
    end
  end

  def edit; 
  end

  def update
    if @blog.update(blog_params)
      redirect_to @blog
    else
      render :edit
    end
  end

  def publish
    @blog.update(ispublished: !@blog.ispublished)
    redirect_to blog_path(@blog)
  end

  def destroy
    @blog.destroy
    redirect_to root_path
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :body)
  end

  def find_id
    @blog = Blog.find_by(slug: params[:id])
  end
end

MicroBlog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.create(comment_params)
    redirect_to blog_path(@blog)
  end

  private

  def comment_params
    params.require(:comment).permit(:name, :body)
  end
end

MicroBlog/app/helpers/application_helper.rb
module ApplicationHelper
end

MicroBlog/app/helpers/blogs_helper.rb
module BlogsHelper
  def blog_status(blog)
    blog.ispublished ? 'Unpublish' : 'Publish'
  end
end

MicroBlog/app/helpers/comments_helper.rb
module CommentsHelper
end

MicroBlog/app/views/blogs/_form.html.erb
<%= form_with model: blog do |blog| %>
  <div>
    <%= blog.label :title %><br>
    <%= blog.text_field :title %>
  </div>

  <div>
    <%= blog.label :body %><br>
    <%= blog.text_area :body %><br>

  </div>

  <div>
    <%= blog.submit %>
  </div>
<% end %>

MicroBlog/app/views/blogs/edit.html.erb
<h1> Edit Blog </h1>
<%= render "form", blog: @blog %>

MicroBlog/app/views/blogs/index.html.erb
<h1>MicroBlog</h1>
<ul>
  <% @blogs.each do |blog| %>
  <li>
  <% if blog.ispublished? %>
    <div class="blog">  
      <%= link_to blog.title, blog %>
      <span> Body :  </span>
      <%= blog.body%> 
      <%= blog.ispublished %>
    <% else %>
    <h1> Else Part </h1>
    <% end %>
  </li>
  <% end %>
</ul>

<%= link_to "New Blog", new_blog_path %>

MicroBlog/app/views/blogs/new.html.erb
<h1> New Blog</h1>
<%= render "form", blog: @blog %>
<% @blog.ispublished = false %>

MicroBlog/app/views/blogs/show.html.erb
<h1> This is <%= @blog.id %> Blog</h1>
    <p>
    <%= @blog.title %>
    </p>
    <span> Body :  </span>
    <p>
    <%= @blog.body %>
    </p>

  <%= link_to "Edit", edit_blog_path(@blog) %></li>

  <%= link_to "Destroy", blog_path(@blog), method: :delete %>

  <%= link_to blog_status(@blog), publish_blog_path(@blog) %>

<h2>Comment</h2>
<%= render @blog.comments %>
<br>
<h2>Add comment:</h2>
<%= render 'comments/form' %>

MicroBlog/app/views/comments/_comment.html.erb
<p>
  <strong>Name:</strong>
  <%= comment.Name%>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

MicroBlog/app/views/comments/_form.html.erb
<%= form_with model: [ @blog, @blog.comments.build ] do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

MicroBlog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MICROBLOG</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>